services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: twimi
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - 3306:3306
