[target.aarch64-apple-darwin]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=mold"]

[env]
DATABASE_URL = "mysql://docker:docker@127.0.0.1:3306/twimi"

[features]
default = []
offline = ["sqlx/offline"]
