openapi: 3.0.0
x-stoplight:
  id: nyqjerzplm2ns
info:
  title: Twimi
  version: '1.0'
  description: Twimi api
servers:
  - url: 'http://localhost:3000'
paths:
  /login:
    post:
      summary: ''
      operationId: post-login
      responses:
        '200':
          description: OK
          headers:
            Location:
              schema:
                type: string
              description: /tweets
          content:
            application/json:
              schema:
                type: object
                x-examples:
                  example-1:
                    access_token: token
                properties:
                  access_token:
                    type: string
                  refresh_token:
                    type: string
                  user_id:
                    type: integer
                  username:
                    type: string
                  created_at:
                    type: string
                    format: date-time
                  updated_at:
                    type: string
                    format: date-time
                  image_url:
                    type: string
                    format: uri
                  is_official:
                    type: boolean
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
      requestBody:
        content:
          application/json:
            schema:
              type: object
              x-examples:
                example-1:
                  email: user@example.com
                  password: password
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
                - username
                - password
          application/xml:
            schema:
              type: object
              properties: {}
        description: ''
      parameters: []
  /tweets:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    tweet_id:
                      type: integer
                    user_id:
                      type: integer
                    content:
                      type: string
                    created_at:
                      type: string
                      format: date-time
                    updated_at:
                      type: string
                      format: date-time
              examples:
                example-1:
                  value:
                    - tweet_id: 0
                      user_id: 0
                      content: string
                      created_at: '2019-08-24T14:15:22Z'
                      updated_at: '2019-08-24T14:15:22Z'
        '303':
          description: See Other
          headers:
            Location:
              schema:
                type: string
              description: redirect to `/login`
      operationId: get-tweets
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
        description: ''
      parameters:
        - schema:
            type: string
          in: header
          name: Authorized
      description: '  '
    post:
      summary: ''
      operationId: post-tweets
      responses:
        '303':
          description: See Other
          headers:
            Location:
              schema:
                type: string
              description: redirect to `/login` if unauthorized
      parameters:
        - schema:
            type: string
          in: header
          name: Authorized
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: string
                content:
                  type: string
components:
  schemas: {}
